jobs:
- job: linux_build
  displayName: Linux Build

  pool:
    name: Azure Pipelines
    vmImage: 'ubuntu-latest'
  workspace:
    clean: all
  steps:
  - script: |
     sudo apt-get update -qq
     sudo apt-get install libcap2-bin libtest-command-perl
    displayName: 'before_install'

  - script: |
     ci/build-4-compile.sh
    displayName: install

  - script: |
     set -ex
     PATH=`pwd`/src:$PATH
     prove ci/test-{01..12}*.pl
     prove ci/test-15*.pl
     ci/test-tarball.sh
    displayName: 'build_test'
